# Generated by Django 4.2 on 2023-04-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
