# Generated by Django 4.2 on 2023-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_salary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
