# Generated by Django 4.2 on 2023-04-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_recruitment_job_description_recruitment_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
    ]
