# Generated by Django 4.2 on 2023-04-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_recruitment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
    ]
