# Generated by Django 4.2 on 2023-04-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_job_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employmentstatus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manager'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.salary'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leavetype'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.performancetype'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.position'),
        ),
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trainingtype'),
        ),
    ]
